### ISSUE TITLE
how to use it with ARCANEDEV/Localization

### ISSUE THREAD

**Issue by ghost** [laravelista/Ekko#4]
Ekko works great but now im using ARCANEDEV/Localization
this works if i dont use Localization

`<li class="{{ Ekko::isActiveURL('dashboard') }}">`

now my urls are changed based on a language /en/dashboard /nl/dashboard etc
and `<li class="{{ Ekko::isActiveURL('dashboard') }}">` is not working anymore

**Comment by mabasic** [comment]
There are two ways and scenarios to use it when dealing with multilingual websites.

I personally use https://github.com/mcamara/laravel-localization, but I think the same applies.

You can set names on your routes (check Laravel documentation for that) and then use 

```
<li class="{{ Ekko::isActiveRoute('dashboard') }}">
```

or If you really don't want to use named routes you can use:

```
<li class="{{ Ekko::isActiveMatch('dashboard') }}">
```

_But be aware because `isActiveMatch` checks the whole URL for given string._

**Comment by ghost** [comment]
Ok thank you i will use ->name() for my routes
